package Entity.Move;

public enum Target {
    SPECIFIC_MOVE,
    SELECTED_POKEMON_ME_FIRST,
    ALLY,
    USER_FIELD,
    USER_OR_ALLY,
    OPPONENTS_FIELD,
    USER,
    RANDOM_OPPONENT,
    ALL_OTHER_POKEMON,
    SELECTED_POKEMON,
    ALL_OPPONENTS,
    ENTIRE_FIELD,
    USER_AND_ALLIES,
    ALL_POKEMON,
    ALL_ALLIES,
    FAINTING
}